# Generated by Django 3.2.8 on 2021-10-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('poster', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
