# Generated by Django 3.2.8 on 2021-10-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animaze', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
