# Generated by Django 3.2.8 on 2021-10-28 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Animaze', '0002_alter_anime_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('rated', models.CharField(blank=True, max_length=4, null=True)),
                ('year', models.IntegerField()),
                ('director', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=120, null=True)),
                ('value', models.CharField(blank=True, max_length=120, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Animaze.movie')),
            ],
        ),
        migrations.DeleteModel(
            name='Anime',
        ),
    ]
