# Generated by Django 3.2.8 on 2021-10-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animaze', '0003_auto_20211028_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rated',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
